-- MySQL Script generated by MySQL Workbench
-- 05/01/18 16:14:46
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_over_system
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_over_system
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_over_system` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `db_over_system` ;

-- -----------------------------------------------------
-- Table `db_over_system`.`CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_over_system`.`CLIENTE` (
  `idCLIENTE` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `NOME_FANTASIA` VARCHAR(45) NOT NULL COMMENT '',
  `CNPJ` VARCHAR(18) NOT NULL COMMENT '',
  `SERVICO_CONTRATADO` VARCHAR(45) NOT NULL COMMENT '',
  `TELEFONE` VARCHAR(15) NOT NULL COMMENT '',
  `ENDERECO` VARCHAR(100) NOT NULL COMMENT '',
  `EMAIL` VARCHAR(35) NULL COMMENT '',
  `DESCRICAO` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idCLIENTE`)  COMMENT '',
  UNIQUE INDEX `idCLIENTE_UNIQUE` (`idCLIENTE` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_over_system`.`PERFIL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_over_system`.`PERFIL` (
  `idPERFIL` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `PERFIL` VARCHAR(45) NOT NULL COMMENT '',
  `STATUS` INT(1) NOT NULL COMMENT '',
  PRIMARY KEY (`idPERFIL`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_over_system`.`USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_over_system`.`USUARIO` (
  `idUSUARIO` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `USERNAME` VARCHAR(45) NOT NULL COMMENT '',
  `SENHA` VARCHAR(45) NOT NULL COMMENT '',
  `PERFIL_idPERFIL` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idUSUARIO`)  COMMENT '',
  UNIQUE INDEX `idUSUARIO_UNIQUE` (`idUSUARIO` ASC)  COMMENT '',
  UNIQUE INDEX `USERNAME_UNIQUE` (`USERNAME` ASC)  COMMENT '',
  INDEX `fk_USUARIO_PERFIL1_idx` (`PERFIL_idPERFIL` ASC)  COMMENT '',
  CONSTRAINT `fk_USUARIO_PERFIL1`
    FOREIGN KEY (`PERFIL_idPERFIL`)
    REFERENCES `db_over_system`.`PERFIL` (`idPERFIL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_over_system`.`FUNCIONARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_over_system`.`FUNCIONARIO` (
  `idFUNCIONARIO` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `CPF` VARCHAR(15) NOT NULL COMMENT '',
  `NOME` VARCHAR(45) NOT NULL COMMENT '',
  `RG` VARCHAR(9) NOT NULL COMMENT '',
  `DATA_DE_NASCIMENTO` DATE NOT NULL COMMENT '',
  `SEXO` VARCHAR(45) NOT NULL COMMENT '',
  `CARGO` VARCHAR(45) NOT NULL COMMENT '',
  `ENDERECO` VARCHAR(100) NOT NULL COMMENT '',
  `TELEFONE` VARCHAR(45) NULL COMMENT '',
  `EMAIL` VARCHAR(45) NULL COMMENT '',
  `USUARIO_idUSUARIO` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idFUNCIONARIO`)  COMMENT '',
  UNIQUE INDEX `idCADSATRO DE FUNCIONARIO_UNIQUE` (`idFUNCIONARIO` ASC)  COMMENT '',
  INDEX `fk_FUNCIONARIO_USUARIO1_idx` (`USUARIO_idUSUARIO` ASC)  COMMENT '',
  CONSTRAINT `fk_FUNCIONARIO_USUARIO1`
    FOREIGN KEY (`USUARIO_idUSUARIO`)
    REFERENCES `db_over_system`.`USUARIO` (`idUSUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_over_system`.`PRODUTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_over_system`.`PRODUTO` (
  `idPRODUTO` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `NOME` VARCHAR(45) NOT NULL COMMENT '',
  `STATUS` VARCHAR(12) NOT NULL COMMENT '',
  `CATEGORIA` VARCHAR(65) NOT NULL COMMENT '',
  `QUANT_ENTRADA` INT NOT NULL COMMENT '',
  `DATA_ENTRADA` DATE NOT NULL COMMENT '',
  `VALOR_UNIT` DECIMAL(9,2) NOT NULL COMMENT '',
  `QUANT_SAIDA` INT NOT NULL DEFAULT 0 COMMENT '',
  `DATA_SAIDA` DATE NOT NULL COMMENT '',
  PRIMARY KEY (`idPRODUTO`)  COMMENT '',
  UNIQUE INDEX `idPRODUTO_UNIQUE` (`idPRODUTO` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_over_system`.`ESTOQUE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_over_system`.`ESTOQUE` (
  `idESTOQUE` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `QUANT` INT(11) NOT NULL COMMENT '',
  `VALOR_UNIT` DECIMAL(9,2) NOT NULL DEFAULT 0.00 COMMENT '',
  `PRODUTO_idPRODUTO` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idESTOQUE`)  COMMENT '',
  UNIQUE INDEX `idESTOQUE_UNIQUE` (`idESTOQUE` ASC)  COMMENT '',
  INDEX `fk_ESTOQUE_PRODUTO1_idx` (`PRODUTO_idPRODUTO` ASC)  COMMENT '',
  CONSTRAINT `fk_ESTOQUE_PRODUTO1`
    FOREIGN KEY (`PRODUTO_idPRODUTO`)
    REFERENCES `db_over_system`.`PRODUTO` (`idPRODUTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_over_system`.`MENU`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_over_system`.`MENU` (
  `idMENU` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `LINK` VARCHAR(145) NOT NULL COMMENT '',
  `MENU` VARCHAR(45) NOT NULL COMMENT '',
  `STATUS` INT(1) NOT NULL COMMENT '',
  PRIMARY KEY (`idMENU`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_over_system`.`MENU_PERFIL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_over_system`.`MENU_PERFIL` (
  `idMENU` INT NOT NULL COMMENT '',
  `idPERFIL` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idMENU`, `idPERFIL`)  COMMENT '',
  INDEX `fk_MENU_has_PERFIL_PERFIL1_idx` (`idPERFIL` ASC)  COMMENT '',
  INDEX `fk_MENU_has_PERFIL_MENU1_idx` (`idMENU` ASC)  COMMENT '',
  CONSTRAINT `fk_MENU_has_PERFIL_MENU1`
    FOREIGN KEY (`idMENU`)
    REFERENCES `db_over_system`.`MENU` (`idMENU`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_MENU_has_PERFIL_PERFIL1`
    FOREIGN KEY (`idPERFIL`)
    REFERENCES `db_over_system`.`PERFIL` (`idPERFIL`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_over_system`.`SERVICO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_over_system`.`SERVICO` (
  `idSERVICO` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `TIPO` VARCHAR(145) NOT NULL COMMENT '',
  `VALOR` VARCHAR(45) NOT NULL COMMENT '',
  `DATA_INICIAL` VARCHAR(45) NOT NULL COMMENT '',
  `DATA_FINAL` VARCHAR(45) NOT NULL COMMENT '',
  `CLIENTE_idCLIENTE` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idSERVICO`)  COMMENT '',
  INDEX `fk_SERVICO_ CLIENTE1_idx` (`CLIENTE_idCLIENTE` ASC)  COMMENT '',
  CONSTRAINT `fk_SERVICO_ CLIENTE1`
    FOREIGN KEY (`CLIENTE_idCLIENTE`)
    REFERENCES `db_over_system`.`CLIENTE` (`idCLIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_over_system`.`SERVICO_has_FUNCIONARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_over_system`.`SERVICO_has_FUNCIONARIO` (
  `SERVICO_idSERVICO` INT NOT NULL COMMENT '',
  `FUNCIONARIO_idFUNCIONARIO` INT NOT NULL COMMENT '',
  PRIMARY KEY (`SERVICO_idSERVICO`, `FUNCIONARIO_idFUNCIONARIO`)  COMMENT '',
  INDEX `fk_SERVICO_has_FUNCIONARIO_FUNCIONARIO1_idx` (`FUNCIONARIO_idFUNCIONARIO` ASC)  COMMENT '',
  INDEX `fk_SERVICO_has_FUNCIONARIO_SERVICO1_idx` (`SERVICO_idSERVICO` ASC)  COMMENT '',
  CONSTRAINT `fk_SERVICO_has_FUNCIONARIO_SERVICO1`
    FOREIGN KEY (`SERVICO_idSERVICO`)
    REFERENCES `db_over_system`.`SERVICO` (`idSERVICO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SERVICO_has_FUNCIONARIO_FUNCIONARIO1`
    FOREIGN KEY (`FUNCIONARIO_idFUNCIONARIO`)
    REFERENCES `db_over_system`.`FUNCIONARIO` (`idFUNCIONARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_over_system`.`SERVICO_has_PRODUTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_over_system`.`SERVICO_has_PRODUTO` (
  `SERVICO_idSERVICO` INT NOT NULL COMMENT '',
  `PRODUTO_idPRODUTO` INT NOT NULL COMMENT '',
  PRIMARY KEY (`SERVICO_idSERVICO`, `PRODUTO_idPRODUTO`)  COMMENT '',
  INDEX `fk_SERVICO_has_PRODUTO_PRODUTO1_idx` (`PRODUTO_idPRODUTO` ASC)  COMMENT '',
  INDEX `fk_SERVICO_has_PRODUTO_SERVICO1_idx` (`SERVICO_idSERVICO` ASC)  COMMENT '',
  CONSTRAINT `fk_SERVICO_has_PRODUTO_SERVICO1`
    FOREIGN KEY (`SERVICO_idSERVICO`)
    REFERENCES `db_over_system`.`SERVICO` (`idSERVICO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SERVICO_has_PRODUTO_PRODUTO1`
    FOREIGN KEY (`PRODUTO_idPRODUTO`)
    REFERENCES `db_over_system`.`PRODUTO` (`idPRODUTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
