-- MySQL Script generated by MySQL Workbench
-- 05/20/18 21:05:16
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_over_system
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_over_system
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_over_system` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `db_over_system` ;

-- -----------------------------------------------------
-- Table `db_over_system`.`CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_over_system`.`CLIENTE` (
  `idcliente` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nome_fantasia` VARCHAR(85) NOT NULL COMMENT '',
  `cnpj` VARCHAR(18) NOT NULL COMMENT '',
  `servico_contratado` VARCHAR(45) NOT NULL COMMENT '',
  `valor_servico` DECIMAL(9,2) NOT NULL COMMENT '',
  `data_adesao` DATE NOT NULL COMMENT '',
  `telefone` VARCHAR(15) NOT NULL COMMENT '',
  `endereco` VARCHAR(100) NOT NULL COMMENT '',
  `email` VARCHAR(35) NULL COMMENT '',
  `descricao` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idcliente`)  COMMENT '',
  UNIQUE INDEX `idCLIENTE_UNIQUE` (`idcliente` ASC)  COMMENT '',
  UNIQUE INDEX `CNPJ_UNIQUE` (`cnpj` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_over_system`.`PERFIL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_over_system`.`PERFIL` (
  `idperfil` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `perfil` VARCHAR(45) NOT NULL COMMENT '',
  `status` INT(1) NOT NULL COMMENT '',
  PRIMARY KEY (`idperfil`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_over_system`.`USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_over_system`.`USUARIO` (
  `idusuario` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `username` VARCHAR(45) NOT NULL COMMENT '',
  `senha` VARCHAR(45) NOT NULL COMMENT '',
  `perfil_idperfil` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idusuario`)  COMMENT '',
  UNIQUE INDEX `idUSUARIO_UNIQUE` (`idusuario` ASC)  COMMENT '',
  UNIQUE INDEX `USERNAME_UNIQUE` (`username` ASC)  COMMENT '',
  INDEX `fk_USUARIO_PERFIL1_idx` (`perfil_idperfil` ASC)  COMMENT '',
  CONSTRAINT `fk_USUARIO_PERFIL1`
    FOREIGN KEY (`perfil_idperfil`)
    REFERENCES `db_over_system`.`PERFIL` (`idperfil`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_over_system`.`FUNCIONARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_over_system`.`FUNCIONARIO` (
  `idfuncionario` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `cpf` VARCHAR(14) NOT NULL COMMENT '',
  `nome` VARCHAR(45) NOT NULL COMMENT '',
  `rg` VARCHAR(9) NOT NULL COMMENT '',
  `data_de_nascimento` DATE NOT NULL COMMENT '',
  `sexo` VARCHAR(12) NOT NULL COMMENT '',
  `cargo` VARCHAR(45) NOT NULL COMMENT '',
  `endereco` VARCHAR(100) NOT NULL COMMENT '',
  `telefone` VARCHAR(18) NOT NULL COMMENT '',
  `email` VARCHAR(45) BINARY NULL COMMENT '',
  `usuario_idusuario` INT NULL COMMENT '',
  PRIMARY KEY (`idfuncionario`)  COMMENT '',
  UNIQUE INDEX `idCADSATRO DE FUNCIONARIO_UNIQUE` (`idfuncionario` ASC)  COMMENT '',
  INDEX `fk_FUNCIONARIO_USUARIO1_idx` (`usuario_idusuario` ASC)  COMMENT '',
  UNIQUE INDEX `CPF_UNIQUE` (`cpf` ASC)  COMMENT '',
  UNIQUE INDEX `RG_UNIQUE` (`rg` ASC)  COMMENT '',
  CONSTRAINT `fk_FUNCIONARIO_USUARIO1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `db_over_system`.`USUARIO` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_over_system`.`PRODUTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_over_system`.`PRODUTO` (
  `idproduto` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(45) NOT NULL COMMENT '',
  `quantidade` INT NOT NULL COMMENT '',
  `valor_unit` DECIMAL(9,2) NOT NULL COMMENT '',
  `categoria` VARCHAR(65) NOT NULL COMMENT '',
  PRIMARY KEY (`idproduto`)  COMMENT '',
  UNIQUE INDEX `idPRODUTO_UNIQUE` (`idproduto` ASC)  COMMENT '',
  UNIQUE INDEX `NOME_UNIQUE` (`nome` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_over_system`.`MENU`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_over_system`.`MENU` (
  `idmenu` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `link` VARCHAR(145) NOT NULL COMMENT '',
  `menu` VARCHAR(45) NOT NULL COMMENT '',
  `status` INT(1) NOT NULL COMMENT '',
  `icone` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idmenu`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_over_system`.`MENU_PERFIL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_over_system`.`MENU_PERFIL` (
  `idmenu` INT NOT NULL COMMENT '',
  `idperfil` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idmenu`, `idperfil`)  COMMENT '',
  INDEX `fk_MENU_has_PERFIL_PERFIL1_idx` (`idperfil` ASC)  COMMENT '',
  INDEX `fk_MENU_has_PERFIL_MENU1_idx` (`idmenu` ASC)  COMMENT '',
  CONSTRAINT `fk_MENU_has_PERFIL_MENU1`
    FOREIGN KEY (`idmenu`)
    REFERENCES `db_over_system`.`MENU` (`idmenu`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_MENU_has_PERFIL_PERFIL1`
    FOREIGN KEY (`idperfil`)
    REFERENCES `db_over_system`.`PERFIL` (`idperfil`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_over_system`.`INSTALACAO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_over_system`.`INSTALACAO` (
  `idinstalacao` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `tipo` VARCHAR(145) NOT NULL COMMENT '',
  `valor` DECIMAL(9,2) NOT NULL COMMENT '',
  `data_inicial` DATE NOT NULL COMMENT '',
  `data_final` DATE NOT NULL COMMENT '',
  `cliente_idcliente` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idinstalacao`)  COMMENT '',
  INDEX `fk_SERVICO_ CLIENTE1_idx` (`cliente_idcliente` ASC)  COMMENT '',
  CONSTRAINT `fk_SERVICO_ CLIENTE1`
    FOREIGN KEY (`cliente_idcliente`)
    REFERENCES `db_over_system`.`CLIENTE` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_over_system`.`INSTALACAO_PRODUTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_over_system`.`INSTALACAO_PRODUTO` (
  `idinstalacao` INT NOT NULL COMMENT '',
  `idproduto` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idinstalacao`, `idproduto`)  COMMENT '',
  INDEX `fk_INSTALACAO_has_PRODUTO_PRODUTO1_idx` (`idproduto` ASC)  COMMENT '',
  INDEX `fk_INSTALACAO_has_PRODUTO_INSTALACAO1_idx` (`idinstalacao` ASC)  COMMENT '',
  CONSTRAINT `fk_INSTALACAO_has_PRODUTO_INSTALACAO1`
    FOREIGN KEY (`idinstalacao`)
    REFERENCES `db_over_system`.`INSTALACAO` (`idinstalacao`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_INSTALACAO_has_PRODUTO_PRODUTO1`
    FOREIGN KEY (`idproduto`)
    REFERENCES `db_over_system`.`PRODUTO` (`idproduto`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_over_system`.`INSTALACAO_FUNCIONARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_over_system`.`INSTALACAO_FUNCIONARIO` (
  `idinstalacao` INT NOT NULL COMMENT '',
  `idfuncionario` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idinstalacao`, `idfuncionario`)  COMMENT '',
  INDEX `fk_INSTALACAO_has_FUNCIONARIO_FUNCIONARIO1_idx` (`idfuncionario` ASC)  COMMENT '',
  INDEX `fk_INSTALACAO_has_FUNCIONARIO_INSTALACAO1_idx` (`idinstalacao` ASC)  COMMENT '',
  CONSTRAINT `fk_INSTALACAO_has_FUNCIONARIO_INSTALACAO1`
    FOREIGN KEY (`idinstalacao`)
    REFERENCES `db_over_system`.`INSTALACAO` (`idinstalacao`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_INSTALACAO_has_FUNCIONARIO_FUNCIONARIO1`
    FOREIGN KEY (`idfuncionario`)
    REFERENCES `db_over_system`.`FUNCIONARIO` (`idfuncionario`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_over_system`.`LOG`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_over_system`.`LOG` (
  `idlog` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(45) NOT NULL COMMENT '',
  `data` DATE NOT NULL COMMENT '',
  `funcionario_idfuncionario` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idlog`)  COMMENT '',
  INDEX `fk_LOG_FUNCIONARIO1_idx` (`funcionario_idfuncionario` ASC)  COMMENT '',
  CONSTRAINT `fk_LOG_FUNCIONARIO1`
    FOREIGN KEY (`funcionario_idfuncionario`)
    REFERENCES `db_over_system`.`FUNCIONARIO` (`idfuncionario`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
